name: Workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node:20  # use a specific Node version
    defaults:
      run:
        working-directory: VmBDEExam

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /public_html/test/todo/
          local-dir: VmBDEExam/dist/
          timeout: 60000
          log-level: verbose

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Update APT
        run: apt-get update

      - name: Install Chromium
        run: |
          apt-get install -y chromium
          ln -s /usr/bin/chromium /usr/bin/google-chrome || true
          ln -s /usr/bin/chromium /usr/bin/chromium-browser || true

      - name: Run TestCafe tests
        run: |
          testcafe "chromium:headless --ignore-certificate-errors" test/* \
            --page-request-timeout 120000 \
            --retry-test-pages \
            --quarantine-mode \
            --disable-page-caching
