name: Workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-22.04
    environment: Test
    defaults:
      run:
        working-directory: VmBDEExam
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps-implicit
          port: 990
          server-dir: public_html/test/todo/
          local-dir: VmBDEExam/dist/
          timeout: 180000
          max-tries: 5
          security: loose
          exclude: |
            **/.git*
            **/node_modules/**
            **/test/**
            **/tests/**
            **/*.map
          log-level: verbose

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome VmBDEExam/test/*"

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: VmBDEExam/dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-22.04
    environment: Live
    steps:
      - name: Load Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: VmBDEExam/dist/

      - name: FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }} # e.g. ftp.simply.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps-implicit
          port: 990
          server-dir: public_html/live/todo/
          local-dir: VmBDEExam/dist/
          timeout: 180000
          max-tries: 5
          security: loose
          exclude: |
            **/.git*
            **/node_modules/**
            **/test/**
            **/tests/**
            **/*.map
          log-level: verbose