name: Workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-22.04
    environment: Test
    defaults:
      run:
        working-directory: VmBDEExam
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /public_html/test/todo/
          local-dir: VmBDEExam/dist/
          timeout: 60000
          log-level: verbose

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome VmBDEExam/test/*"

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: VmBDEExam/dist/

  deployment:
  needs: integration-delivery
  runs-on: ubuntu-22.04
  environment: Live
  steps:
    - name: Load Artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: VmBDEExam/dist/

    - name: Debug list files
      run: ls -R VmBDEExam/dist/

    - name: FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: /public_html/live/todo/
        local-dir: VmBDEExam/dist/
        timeout: 180000
        log-level: verbose
        passive: true
        retry: true
        retry-count: 3

